base_branch: master

pr_body_template: |
  ## What

  Describe the change.

  ## Why

  Describe the business reason for the change.

  ## How

  Describe the implementation.

  ## Testing

  Describe how to test your changes.

deploy:
  command: script/bash/deploy.sh {branch}
  arguments: branch
