default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reconnect: false
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
  database: system_variable_dummy_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
  database: system_variable_dummy_test
  socket: /tmp/mysql.sock

production:
  <<: *default
